### PR TITLE
[Docs] MLPRegressor Translation

### PR DESCRIPTION
**Pull request by jamesb93**
Translation of the MLPRegressor SC help file

### CODE REVIEW

**Comment by jamesb93** [comment]
This should actually be updated to accomodate changes present in:

https://github.com/flucoma/flucoma-docs/pull/109/

**Review by tremblap — APPROVED** [review]
this translation is very dry. I kind of miss the fun synth example although I understand it is too much for a helpfile. this is where the learn page shines with all the cross links and all.

**Comment by jamesb93** [comment]
> this translation is very dry. I kind of miss the fun synth example although I understand it is too much for a helpfile. this is where the learn page shines with all the cross links and all.

Indeed this was the criticism that was presented to me when it used to have the musical example in it. I think that these monolith objects should link out very clearly to more full examples to help bridge the gap in the CCE and with learn. I made an issue here to track it:

https://github.com/flucoma/flucoma-max/issues/227

**Comment by jamesb93** [comment]
> ok that sounds good. the more I think about it the more I think you're right.

Can I merge this then with the follow-up for linking out to bigger tutorials as the plan?

**Comment by tremblap** [comment]
yep

**Pull request merged**
