### PR TITLE
MaxWrapper: Add choices param (list of symbols <-> bitset)

### PR DESCRIPTION
**Pull request by weefuzzy**
See https://github.com/flucoma/flucoma-core/pull/108

### CODE REVIEW

**Comment by tremblap** [comment]
a max-specific question: when I choose attrui for `select` the full list is there, which is great.

if I type in there whatever, it autocorrects to kurtosis though, which is a bug?

Also when I send a message `select mean` the attrui corrects to kurtosis again.

finally, when I ask for mean only, I get 2 values (the kurtosis and its derivative - I expect 2 values but not the kurtosis :))

`reset` works as expected - I get back the full list in the attrui

**Comment by tremblap** [comment]
(more info: I get the same behaviour in Pd)

**Comment by weefuzzy** [comment]
Weird – I thought that was something I'd fixed early in development. I must have not paid attention when pushing / branch switching and junked some changes by accident. Anyway, it should work now.

**Comment by tremblap** [comment]
I filled the feedback in the core repo https://github.com/flucoma/flucoma-core/pull/108 - it worked but broke everything else strangely

**Comment by jamesb93** [comment]
I'm not sure if this related to the Max bit of code or the core bit of code @weefuzzy or what the limitations and expectations are but...

When I set the `@select` in the box I get what I expect, but sending messages on the fly for the rt versions updates the parameter but it is not reflected in the output. I get a similar behaviour with the buffer versions, where putting what I want in the box gives me I expect, however the `@features` buffer doesn't resize as I would expect. Patch to demonstrate:

```
<pre><code>
----------begin_max5_patcher----------
1061.3ocuX0saixCD85jmBKtakxhv176dUeH9t6SqpbHlDRM1QXSSqVs6y9N
1PZS2RHzBoRsgvvfGeNLyYFxuVtvas5It1C8Cz+iVr3WKWrvYxZXQ24K7pXO
kKXZmad4ppJtz3sp8ZF9SFmc52PR0QDS+.pPUinHytR4VMZciA9JGNVTvqQG
KEBTMuhUJAeQLDAkuiIkbgO5+.2xURCr7ZjPod.UqZ1tS7LXstlmabqrcwJJ
q0lWuUMXz54oMknTxyUMR2NKpy3gZtFVYloTIuuWOjMUkRA23.J9UipFyIqA
cVK23.sZ89uSCNE1CLStEz2a2qsbZVRfevJDgDYOfibmkD5Gf9o8d98xk1OV
MQtm7sNFA3b8JzQNRy4nRfEekh7cWDsUo1zKMQlDIPxFfDRxbvFmj4G8BIPo
eRRnPnfsyovAYDULWbhGO.HurWqYUbCu9dtjsVvOGbstad9.uEDddqPdqYxs
dne1C9SFB+IwVDGhSr3OpKi3SBeI+HDv2kBTJKT+AU3MdRH6R.EHXfQAzJJ0
tiuXXLew9eoMkpOVJZHVJl3xKhCcYIAzIQSWpTA2JSYECzsUDL4FaEiSXRar
eti8HGDvdjIZ3ZvcPoo2RF5zJYBGfLBCboL3vyKYBS9jjQE.V1V96HCMWXUU
0OvOhz.kv1.JtBgpnXExkp2G.I8BP7EKa5MQfbc4BBMvg81hm4tdosczGqhg
b0JlKqOLTShzzvyx7ilVhOzu0nje.Tg+LhgWDn3jqWh20Hf3PMIbdevVHZJ2
3COd0Gf3VyD5crC7+ftqKYOGp7gAIDLizJAbmV0TmyQ6Q2UvYlF3penbB5fL
zaDF6ktFihHNxRWzaagvdzdkbq3YeV4WTMANbDoJcBfAjIg8KI.FF4GGkEkQ
QA9ve2L8N7Pk+Dba4ej64a1MBozL+rvXHIB8JnwTvVVPZDhj.CkFShxRBg1L
D+HZ.3BB13.+SSCRI1tOQgwAgiuU3bvboCQbccEa0QnItyxl2xi7myEf5QXX
vbjbnK2JYhdAZ7..M1AML08RDw2DYfVYy2pYNGx.mlgrWLGcULSBaewIb7Mo
p3z.Psy9XmC5lIALjXGIMygxNMOL9q5I7k5J1ME3MOA.ODoPwmkAPhylDovL
l5lxYdrH6hdVdj2Gqm.85Y+NnSS6ehP2h5jg+me.G25Ys+V9ncRmtszoWGCk
9xdaCjBTJc+9Hm6DLPG5Rb9XijcLG6hLbjhlgHYeyhqFI7bDIbxWVjFSff9S
H7DCzXdJkNCwIdL.5M9np2vckZASJvgiOvS6IFcDAZNRMhGeb9WlD+NoD1gC
Oxq0c2sKlfH5dky8zUtSKksm5F3yql+X4I+chhdrZPJy.5XvaR4j5dJtsymW
kBBrDzfaiMfVHjNAZIHvpOvZAlSGe4uW9WrF3kMB
-----------end_max5_patcher-----------
</code></pre>
```

**Comment by weefuzzy** [comment]
It's more of an everything-thing, and gets solved by the `max-params` PR, insofar as list sizes (in Max / PD) and buffer sizes (in all) should respond properly.

**Pull request merged**
