### PR TITLE
[Docs] Update fluid.list2buf

### PR DESCRIPTION
**Pull request by jamesb93**
Updates fluid.list2buf help file﻿

### CODE REVIEW

**Review by tremblap — CHANGES_REQUESTED** [review]
looks nice. auto-sizing doesn't shrink the internal buffer - if that is not a bug, we need a comment on the auto-sizing tab saying so.

**Comment by jamesb93** [comment]
> looks nice. auto-sizing doesn't shrink the internal buffer - if that is not a bug, we need a comment on the auto-sizing tab saying so.

I actually don't know and just assumed it was the behaviour of the object. Maybe @weefuzzy can chime in?

**Comment by tremblap** [comment]
I saw the discussion on discord, is that a bug then?

**Comment by jamesb93** [comment]
> An enhancement. IAC, I've said how to enact it, so it could go straight in

If you're happy I shall be your conduit of mighty change.

**Comment by weefuzzy** [comment]
Yay, my son, go forth

**Pull request merged**
