### PR TITLE
[Docs] Standardise SC Translation

### PR DESCRIPTION
**Pull request by jamesb93**
As the title says.

### CODE REVIEW

**Comment by tremblap** [comment]
it works. It is a bit sad that we lost the graphic representation (which I reckon we lost in SC too @tedmoore ) but it is probably more readable. The reference online is still empty, is that normal?

**Comment by tedmoore** [comment]
> It is a bit sad that we lost the graphic representation

I'm not sure what you're referring to. Perhaps it wasn't in the SC example code?

**Comment by tremblap** [comment]
it was: there was a bipolar bar graph for the raw and scaled values. I remember coding it influenced by @weefuzzy 's Max version (translation was in that direction then )

**Comment by tedmoore** [comment]
> it was: there was a bipolar bar graph for the raw and scaled values. I remember coding it influenced by @weefuzzy 's Max version (translation was in that direction then )

Ah, I remember now. Does "it is a bit sad" mean that you want for it to be put back in?

**Comment by tremblap** [comment]
> Ah, I remember now. Does "it is a bit sad" mean that you want for it to be put back in? I'm already on it

it was more to raise a question - was it removed because it was considered confusing (so leave it out) or for another reason?

**Comment by jamesb93** [comment]
> > Ah, I remember now. Does "it is a bit sad" mean that you want for it to be put back in? I'm already on it
> 
> it was more to raise a question - was it removed because it was considered confusing (so leave it out) or for another reason?

It was confusing to me which was my rationale for not questioning it in the review of the SuperCollider pull request.

**Comment by tedmoore** [comment]
> > > Ah, I remember now. Does "it is a bit sad" mean that you want for it to be put back in? I'm already on it
> > 
> > 
> > it was more to raise a question - was it removed because it was considered confusing (so leave it out) or for another reason?
> 
> It was confusing to me which was my rationale for not questioning it in the review of the SuperCollider pull request.

I don't think it's too confusing. I found it a little dry and thought that it didn't really add much. But I don't think it's hurting anything. Generally my approach has been the more angles we can show on things the better.

**Pull request merged**
