### PR TITLE
[Docs] MLPClassifier Translation

### PR DESCRIPTION
**Pull request by jamesb93**
Translation of Ted's work on the SC help files.

This help file will have a strong link to the videos and a bigger example patch to demonstrate the canonical musical application of audio classification. Having this live outside the help file reduces the bloat and "ARGHHHHH" feeling of opening it up.

These connections don't yet exist because these examples don't but there will be an accompanying issue.

### CODE REVIEW

**Comment by jamesb93** [comment]
Issue here: https://github.com/flucoma/flucoma-max/issues/227

**Comment by jamesb93** [comment]
On one hand, I think that this help file is messy (again) and not that clear. What do you think @tremblap?

**Comment by jamesb93** [comment]
Should be updated to accomodate changes in:

https://github.com/flucoma/flucoma-docs/pull/109/

**Review by tremblap — APPROVED** [review]
good translation a little more dense than the regressor but the 2nd tab makes it a little more fun.

**Pull request merged**
