### PR TITLE
Trigger compilation from CI on PRs

### PR DESCRIPTION
**Pull request by jamesb93**
Triggers a custom version of the nightly build CI action on PRs. This gives an inline report of whether the build worked for each PR.

### CODE REVIEW

**Comment by tremblap** [comment]
funnilly the winbuild is failing on this :)

**Comment by jamesb93** [comment]
> funnilly the winbuild is failing on this :)

It will fail until the changes from https://github.com/flucoma/flucoma-max/pull/95 get merged.

**Comment by tremblap** [comment]
I could guess that - I just resisted merging 95

**Comment by jamesb93** [comment]
Await the reviewers review :)

**Review by weefuzzy — APPROVED** [review]

**Pull request merged**
