### PR TITLE
[Docs] Transients Family Translation 

### PR DESCRIPTION
**Pull request by jamesb93**
- translate transientslice
- translate buftransientslice
- fluid.transients~ translation
- cosmetic
- translate buftransients

### CODE REVIEW

**Review by tremblap — COMMENTED** [review]
these are ok. buftransient could be improved in 2 ways

- as discussed with @tedmoore for the SC one, we should look at 2 seconds instead of a long file since looking at it like this shows very little

- I prefer the stereo example to be on dual mono as it illustrates more the independance of the channels (the old guit+piano files was more explicit despite 'costing' a bit bufcompose.

**Comment by jamesb93** [comment]
> * as discussed with @tedmoore for the SC one, we should look at 2 seconds instead of a long file since looking at it like this shows very little

image

I think this pretty clear compared?

> * I prefer the stereo example to be on dual mono as it illustrates more the independance of the channels (the old guit+piano files was more explicit despite 'costing' a bit bufcompose.

I agree!

**Comment by tedmoore** [comment]
I remember a conversation with @tremblap that was rather than having stereo examples in all the example codes we should make a stereo processing overview somewhere...I've been deleting all the stereo processing examples from the code (:eyes:)

**Comment by jamesb93** [comment]
I agree it would be much easier to maintain and deal with to be honest.

I'm on board for the idea of shared tutorials/references/guides over patch specific ones. It would be important to caveat the difference between everything else and the `BufNMF` behaviour though (and possibly related objects but I don't remember off the top of my head).

**Comment by tedmoore** [comment]
> It would be important to caveat the difference between everything else and the `BufNMF` behaviour though

Can you be more specific about what the difference is in this case? 

In general I have been checking that the RST has information about "what happens when a multichannel file is used" which they do.

**Pull request merged**
